version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/reverse-todo-backend:latest
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb+srv://foderac3:fode2002@cluster.u4kc60a.mongodb.net/?retryWrites=true&w=majority&appName=CLUSTER
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
    image: ${DOCKER_USERNAME}/reverse-todo-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:5000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
